# Generated by Django 4.2 on 2026-05-16 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="client_type",
            field=models.CharField(
                choices=[
                    ("regular", "Regular"),
                    ("Distribuidor", "Distribuidor"),
                    ("Almacen", "Almacen"),
                    ("Entrenador", "Entrenador"),
                ],
                default="regular",
                max_length=20,
            ),
        ),
    ]
