# Generated by Django 6.0.5 on 2026-05-28 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_client_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='cedula',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Cédula / NIT'),
        ),
        migrations.AddField(
            model_name='client',
            name='municipio',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Descuento base del cliente (%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='client',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Observaciones'),
        ),
    ]
