# Generated by Django 4.2.30 on 2026-05-15 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='talla',
            field=models.CharField(blank=True, choices=[('35', 'T-35'), ('36', 'T-36'), ('37', 'T-37'), ('38', 'T-38'), ('39', 'T-39'), ('40', 'T-40'), ('41', 'T-41'), ('42', 'T-42'), ('43', 'T-43'), ('44', 'T-44'), ('45', 'T-45'), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL'), ('1', 'N°1'), ('2', 'N°2'), ('3', 'N°3'), ('4', 'N°4'), ('5', 'N°5'), ('U', 'Única')], default='', max_length=10, verbose_name='Talla'),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_stock',
            field=models.PositiveIntegerField(default=5, help_text='Umbral mínimo de stock'),
        ),
    ]
