# Generated by Django 6.0.5 on 2026-05-28 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_saleitem_color_vendido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='discount_applied',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Descuento aplicado (%)'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('completed', 'Completada'), ('cancelled', 'Anulada')], default='completed', max_length=20),
        ),
    ]
